### ISSUE TITLE
Code icon missing

### ISSUE THREAD

**Issue by ElHyperion** [Joshaby/Papirus-Nord#3]
The **folder-*-code** icon and its color variations are missing from your icons, you might want to add it to your package aswell. I'm attaching a screenshot of how it looks in the Papirus package. There might be other icons missing aswell, not just the code one, but I haven't searched for them.

![image](https://user-images.githubusercontent.com/5313557/109396731-4736d180-7933-11eb-98fb-602c7d406697.png)

**Comment by Joshaby** [comment]
Hello, thanks for reporting this! I'm doing a new update!

**Comment by Joshaby** [comment]
The missing icon has already been placed in the icon theme!
