### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by brymer-meneses** [Joshaby/Papirus-Nord#5]
I installed the `Papirus-Icons` using the following command 
```
wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR="$HOME/.icons" sh
```

I then cloned this repository from my `Downloads` folder in my home directory. 
I then ran `sudo papirus-folders -t Papirus-Dark -C frostblue2`. It worked fine, without any signs of errors.

However, the icons are still not changed. 

Did I miss something?

**Comment by Joshaby** [comment]
Did you run the Papirus-Nord installation script? If not, you need to do that!

**Comment by brymer-meneses** [comment]
I did, it still didn't work.

**Comment by brymer-meneses** [comment]
I am using GNOME 3.38 on Pop OS

**Comment by brymer-meneses** [comment]
I finally figured out what was wrong. Here's how I fixed it.

Instead of installing the Papirus Icons on the home directory, I installed it on the root directory using this command. It is from the `readme.md` on their repo.
```
wget -qO- https://git.io/papirus-icon-theme-install | sh
```
I then deleted all the icons in the home directory and did all the same steps.

Thank you for this amazing repo!
